#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("Eradio.Resource", IsApplication=true)]

namespace Eradio
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues ();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Alert = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Edance = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Ehit = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Erock = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Eua = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Exit = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Icon = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Logo = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int Play = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int Settings = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int Stop = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int Ukraine = 2130837515;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050004
			public const int btnPlay = 2131034116;
			
			// aapt resource value: 0x7f050001
			public const int iViewArtist = 2131034113;
			
			// aapt resource value: 0x7f050005
			public const int lViewHistoryPlay = 2131034117;
			
			// aapt resource value: 0x7f050008
			public const int linearLayout1 = 2131034120;
			
			// aapt resource value: 0x7f050003
			public const int tViewArtist = 2131034115;
			
			// aapt resource value: 0x7f050009
			public const int tViewTime = 2131034121;
			
			// aapt resource value: 0x7f050002
			public const int tViewTrack = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int tableLayout1 = 2131034112;
			
			// aapt resource value: 0x7f050007
			public const int tableRow1 = 2131034119;
			
			// aapt resource value: 0x7f050006
			public const int textView1 = 2131034118;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ActMain = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int AnimCombo = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int HistoryItem = 2130903042;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int PlayListName = 2130968576;
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
